"""empty message

Revision ID: 037e6cdde755
Revises: e16fe3c6c6a6
Create Date: 2016-12-01 11:13:31.342451

"""

# revision identifiers, used by Alembic.
revision = '037e6cdde755'
down_revision = 'e16fe3c6c6a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'locations', ['location'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    ### end Alembic commands ###
