"""empty message

Revision ID: 15cec2854d30
Revises: c73b6453113d
Create Date: 2017-01-18 13:38:45.628834

"""

# revision identifiers, used by Alembic.
revision = '15cec2854d30'
down_revision = 'c73b6453113d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    ### end Alembic commands ###
