"""empty message

Revision ID: 59b8a4d11b04
Revises: 84a773abc1d1
Create Date: 2017-01-10 19:13:56.882249

"""

# revision identifiers, used by Alembic.
revision = '59b8a4d11b04'
down_revision = '84a773abc1d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'user_id')
    ### end Alembic commands ###
