"""empty message

Revision ID: 64e8f8005ff1
Revises: f3f14a773f35
Create Date: 2017-01-17 11:44:26.929970

"""

# revision identifiers, used by Alembic.
revision = '64e8f8005ff1'
down_revision = 'f3f14a773f35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_area_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_area_code', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
