"""empty message

Revision ID: 84a773abc1d1
Revises: 705611f0b864
Create Date: 2017-01-10 17:56:16.267228

"""

# revision identifiers, used by Alembic.
revision = '84a773abc1d1'
down_revision = '8f9dadf6651c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('days_notice', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('location_id', sa.Integer(), nullable=True))
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'locations', ['location_id'], ['id'])
    op.drop_column('notifications', 'user_id')
    op.add_column('users', sa.Column('phone_area_code', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'phone_area_code')
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_column('notifications', 'location_id')
    op.drop_column('notifications', 'location')
    op.drop_column('notifications', 'days_notice')
    ### end Alembic commands ###
