"""empty message

Revision ID: b34910c7fe62
Revises: e38e98ec83cc
Create Date: 2016-12-01 10:10:42.507992

"""

# revision identifiers, used by Alembic.
revision = 'b34910c7fe62'
down_revision = 'e38e98ec83cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    ### end Alembic commands ###
