"""empty message

Revision ID: e16fe3c6c6a6
Revises: b34910c7fe62
Create Date: 2016-12-01 10:12:29.184315

"""

# revision identifiers, used by Alembic.
revision = 'e16fe3c6c6a6'
down_revision = 'b34910c7fe62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    ### end Alembic commands ###
